### ISSUE TITLE
Updated release for Windows

### ISSUE THREAD

**Issue by tech189** [apngasm/apngasm#99]
It would be good if you could add an updated built release for Windows - the latest I can find is for v3.1.0 in https://github.com/apngasm/apngasm/releases/tag/3.1.1 from 2014! (At the moment the README points to the releases page for downloads for Windows but there aren't any for the most recent versions)

**Comment by oddMLan** [comment]
It was bothering me too, so I made a build following the build instructions for MSYS2. Sadly, I wasnt able to run it.
![image](https://user-images.githubusercontent.com/7278372/160261182-37455465-d08c-404e-bfde-b6a9f19eac55.png)

**Comment by Kagetsuki** [comment]
I'm afraid nobody maintaining this is actually a regular Windows user, but I can say that with MSYS2 it's being built with the libraries and subsystem within MSYS2 so you need to have MSYS2 lib/bin paths and environment variables mapped in Windows to use it outside of MSYS2. The other solution would be to revamp the packaging system to bundle all the dependencies, but if we're putting that much effort into it there's many other issues that would be taking higher priority, including revamping the build system itself. I'm going to leave this issue open in the hopes that someone who's more familiar with Windows will be able to handle this.

**Comment by laggykiller** [comment]
Tried to build following instructions in https://github.com/apngasm/apngasm/blob/master/docs/building/win/instructions.md

Old version of apngams could be built on Windows, so I have done git bisect to find the culprit.

The first commit that caused building to fail on Windows is de1c87cd7696384be3235eb07766766891474e09:

`LINK : fatal error LNK1181: cannot open input file 'stdc++fs.lib'`

However, that could be easily solved (and had been solved) by removing `stdc++fs` from `target_link_libraries()` in CMakeLists.txt.

The next commit was 40425b82ea5398e0c5be92de8749dd4a710508f0 but looks innocent.

The real problematic commit is 553cce10585283fabc1053977a09ad976aa3e2f0:

```
D:\Downloads\apngasm\cli\..\lib\src\apngasm.h(12,10): fatal  error C1083: Cannot open include file: 'png.h': No such file or directo
ry [D:\Downloads\apngasm\build\cli\apngasm-cli.vcxproj]
  options.cpp
D:\Downloads\apngasm\cli\..\lib\src\apngasm.h(12,10): fatal  error C1083: Cannot open include file: 'png.h': No such file or directo
ry [D:\Downloads\apngasm\build\cli\apngasm-cli.vcxproj]
  cli.cpp
D:\Downloads\apngasm\cli\..\lib\src\apngasm.h(12,10): fatal  error C1083: Cannot open include file: 'png.h': No such file or directo
ry [D:\Downloads\apngasm\build\cli\apngasm-cli.vcxproj]
```

I am looking further into this, but note that I don't have experience in C++ programming, so I would need some help here.

**Comment by laggykiller** [comment]
Not sure what had happened, but seems like I have found the solution. I have opened a PR: https://github.com/apngasm/apngasm/pull/106

**Comment by laggykiller** [comment]
You can try out the Windows build here: https://github.com/laggykiller/apngasm/releases/tag/v3.1.10

Note that apngasm.dll and apngasm.exe have to be in the same folder to work
